
export const Archetype = {
    ALL_ROUNDER: "All Rounder",
    RUSHDOWN: "Rush Down",
    PRESSURER: "Pressurer",
    HIT_AND_RUN: "Hit and Run",
    MIX_UP: "Mix Up",
    ZONE_BREAKER: "Zone Breaker",
    DOMINATING: "Dominating",
    POWERHOUSE: "Powerhouse",
    FOOTSIES: "Footsies",
    GLASS_CANNON: "Glass Cannon",
    TAG_TEAM: "Tag Team",
    FIGHTING_GAME_CHARACTER: "Fighting Game Character",
    ZONER: "Zoner",
    BAIT_AND_PUNISH: "Bait and Punish",
    TRAPPER: "Trapper",
    TURTLE: "Turtle",
    KEEP_AWAY: "Keep Away",
    STAGE_CONTROL: "Stage Control",
    NINJA: "Ninja",
    GRAPPLER: "Grappler",
    HALF_GRAPPLER: "Half Grappler",
    HALF_HEALER: "Half Healer",
    DYNAMIC: "Dynamic",
    TANK: "Tank",
    AURA: "Aura",
    FIRST_STRIKE: "First Strike",
    PRECISION: "Precision",
} as const;

export type Archetype = typeof Archetype[keyof typeof Archetype];