
export const CharacterName =
  {
    MARIO: "Mario",
    DONKEY_KONG: "Donkey Kong",
    LINK: "Link",
    SAMUS: "Samus",
    DARK_SAMUS: "Dark Samus",
    YOSHI: "Yoshi",
    KIRBY: "Kirby",
    FOX: "Fox",
    PIKACHU: "Pikachu",
    LUIGI: "Luigi",
    NESS: "Ness",
    CAPTAIN_FALCON: "Captain Falcon",
    JIGGLYPUFF: "Jigglypuff",
    PEACH: "Peach",
    DAISY: "Daisy",
    BOWSER: "Bowser",
    ICE_CLIMBERS: "Ice Climbers",
    SHEIK: "Sheik",
    ZELDA: "Zelda",
    DR_MARIO: "Dr. Mario",
    PICHU: "Pichu",
    FALCO: "Falco",
    MARTH: "Marth",
    LUCINA: "Lucina",
    YOUNG_LINK: "Young Link",
    GANONDORF: "Ganondorf",
    MEWTWO: "Mewtwo",
    ROY: "Roy",
    CHROM: "Chrom",
    MR_GAME_AND_WATCH: "Mr. Game & Watch",
    META_KNIGHT: "Meta Knight",
    PIT: "Pit",
    DARK_PIT: "Dark Pit",
    ZERO_SUIT_SAMUS: "Zero Suit Samus",
    WARIO: "Wario",
    SNAKE: "Snake",
    IKE: "Ike",
    POKEMON_TRAINER: "Pokémon Trainer",
    DIDDY_KONG: "Diddy Kong",
    LUCAS: "Lucas",
    SONIC: "Sonic",
    KING_DEDEDE: "King Dedede",
    OLIMAR: "Olimar",
    LUCARIO: "Lucario",
    ROB: "R.O.B.",
    TOON_LINK: "Toon Link",
    WOLF: "Wolf",
    VILLAGER: "Villager",
    MEGA_MAN: "Mega Man",
    WII_FIT_TRAINER: "Wii Fit Trainer",
    ROSALINA_AND_LUMA: "Rosalina & Luma",
    LITTLE_MAC: "Little Mac",
    GRENINJA: "Greninja",
    PALUTENA: "Palutena",
    PAC_MAN: "Pac-Man",
    ROBIN: "Robin",
    SHULK: "Shulk",
    BOWSER_JR: "Bowser Jr.",
    DUCK_HUNT: "Duck Hunt",
    RYU: "Ryu",
    KEN: "Ken",
    CLOUD: "Cloud",
    CORRIN: "Corrin",
    BAYONETTA: "Bayonetta",
    INKLING: "Inkling",
    RIDLEY: "Ridley",
    SIMON: "Simon",
    RICHTER: "Richter",
    KING_K_ROOL: "King K. Rool",
    ISABELLE: "Isabelle",
    INCINEROAR: "Incineroar",
    PIRANHA_PLANT: "Piranha Plant",
    JOKER: "Joker",
    HERO: "Hero",
    BANJO_AND_KAZOOIE: "Banjo & Kazooie",
    TERRY: "Terry",
    BYLETH: "Byleth",
    MIN_MIN: "Min Min",
    STEVE: "Steve",
    SEPHIROTH: "Sephiroth",
    PYRA_AND_MYTHRA: "Pyra & Mythra",
    KAZUYA: "Kazuya",
    SORA: "Sora",
    MII_BRAWLER: "Mii Brawler",
    MII_SWORDFIGHTER: "Mii Swordfighter",
    MII_GUNNER: "Mii Gunner",
  } as const;

export type CharacterName = typeof CharacterName[keyof typeof CharacterName];